# golangci-lint configuration for ICF Node Benchmark
version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - gosec

issues:
  max-issues-per-linter: 0
  max-same-issues: 0